{% set name = "semi-ate-testers" %}
{% set version = "1.0.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 478cabbc7fc3f72dfff84d11ee98b63c5b1e1c7ec6ca9282e8f27333cdf1bb68

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - semi-ate-common
    - semi-ate-plugins
    - pluggy
    - requests
    - pydantic
  run:
    - python >={{ python_min }}
    - semi-ate-common
    - semi-ate-plugins
    - pluggy
    - requests
    - pydantic
test:
  imports:
    - semi_ate_testers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/semi-ate-testers/
  summary: semi-ate-testers is an example implementation of a plugin that can be consumed by the semi-ate-spyder plugin and the master application.
  license: GPL-2.0-only
  license_file: semi_ate_testers/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
    - heli2src
    - Zlin526F
