{% set name = "semi-ate-testers" %}
{% set version = "1.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-testers-{{ version }}.tar.gz
  sha256: 8da341b4ae6356078fac5d5512a7d2ccadf7c04ce0816435118997ca91c6be06

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - semi-ate-common
    - semi-ate-plugins
    - pluggy
    - requests
    - pydantic
  run:
    - python >=3.8
    - semi-ate-common
    - semi-ate-plugins
    - pluggy
    - requests
    - pydantic
test:
  imports:
    - semi_ate_testers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-testers/
  summary: semi-ate-testers is an example implementation of a plugin that can be consumed by the semi-ate-spyder plugin and the master application.
  license: GPL-2.0-only
  license_file: semi_ate_testers/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
